apiVersion: v1
kind: Service
metadata:
  name: health-service
  namespace: test
spec:
  selector:
    app: health
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8000
      protocol: TCP
  