apiVersion: v1
kind: Service
metadata:
  name: name-service
spec:
  # The selector determines which Pods this Service will target.
  selector:
    app: name
  # The type is ClusterIP by default, but explicitly specifying it improves readability.
  type: NodePort
  ports:
    # Port on which the Service itself is accessible within the cluster
    - port: 3112
      # targetPort is the port on the Pods that the traffic will be forwarded to
      targetPort: 8000
      # The protocol (TCP is the default)
      protocol: TCP
